### ISSUE TITLE
Don't aggregate puzzle inputs 😉

### ISSUE THREAD

**Issue by romietis** [borisdvlpr/aoc2024#1]
https://old.reddit.com/r/adventofcode/wiki/faqs/copyright/inputs

Found [this](https://nicolaiarocci.com/how-to-remove-a-file-from-git-history/) useful to remove files from git history 👀

**Comment by romietis** [comment]
btw quite nice solution for day 3 with `enabled` switch 😄

**Comment by borisdvlpr** [comment]
thanks a lot for your comments!
never really thought of it, thanks for pointing it out. the files were all removed with the suggestion you sent me ;)
